_target_: navsim.agents.transfuser.transfuser_agent.TransfuserAgent
_convert_: 'all'

config:
  _target_: navsim.agents.transfuser.transfuser_config.TransfuserConfig
  _convert_: 'all'
  
  ckpt_path: transfuser_ckpt
  output_dir: None

  scheduler_type: warmup_cos
  
  use_delta_traj: True
  use_beyonddrive: False

  rde_loss_weight: 5.0
  trajectory_weight: 10.0
  bev_semantic_weight: 1.0

  trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    time_horizon: 4
    interval_length: 0.5

  latent: True

checkpoint_path: null
lr: 1e-4
max_epochs: 100